# The URL the site will be built for
base_url = "https://yoloinfinity55.github.io/zolablog/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# The name of the theme to use
theme = "zolarwind"

# The default language for the site
default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Whether to generate a feed
generate_feeds = true

# Taxonomies for the site
taxonomies = [
    { name = "tags", paginate_by = 6, feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "1337"
build_prefix_url = true

# You can add additional syntaxes and themes here
extra_syntaxes_and_themes = ["themes/zolarwind/syntaxes"]

[extra]
# Put all your custom variables here
title = "Zolarwind"

# Path to the language resource files
path_language_resources = "themes/zolarwind/i18n/"

# Optional: Generator version
generator = "Zola"

# Optional: Favicon
favicon_svg = "/img/yin-yang.svg"

# Optional: Copyright notice. {year} is replaced with the current year.
copyright = "Copyright © {year} - Mini John"

# Optional: A brief description for the site banner
# site_description = "A simple blog theme for Zola with Tailwind CSS."

# Optional: A quote for the banner
# quote = { text = "Do or do not. There is no try.", author = "Yoda" }

# Optional: Main navigation menu
menu_pages = [
    { title = "Home", url = "/" },
    { title = "Blog", url = "/blog" },
    { title = "Tags", url = "/tags" },
]

# Optional: Footer navigation
footer_pages = [
    { title = "Imprint", url = "/imprint" },
    { title = "Privacy", url = "/privacy" },
]

# Optional: Social media links
social_links = [
    { name = "github",        enabled = true,  link = "https://github.com/your-github",               svg = '<svg class="h-6 w-6" fill="currentColor" viewBox="0 0 1024 1024"><path d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)"/></svg>' },
]
